swagger: '2.0'
info:
  description: This is API definition for Merkle recommendation system
  version: 2.1.0
  title: Merkle Recommendation System API
host: ikea.com
schemes:
  - http
paths:
  /recom:
    get:
      tags:
        - Recommendation Product List
      summary: Show recommendation product list
      description: returns recommendation product list
      operationId: getProductList
      produces:
        - application/json
      parameters:
        - name: productCategory
          in: query
          description: pass product category
          type: string
      responses:
        '200':
          description: A list of recoomendation products
          schema:
            $ref: '#/definitions/Product'
        '404':
          description: Page not found
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
    description: This is another description
  productstore_auth:
    type: oauth2
    description: This is a standard oauth flow
    authorizationUrl: 'http://productstore.swagger.io/api/oauth/dialog'
    flow: implicit
    scopes:
      write_products: modify products in your account
      read_products: read your products
definitions:
  Product:
    properties:
      recommendList:
        type: object
        example:
          - productID: 134455
          - productID: 234524
          - productID: 192995
          - productID: 199595
      complementaryList:
        type: object
        example:
          - productID: 934455
          - productID: 134524
          - productID: 144995
          - productID: 109595
